- id: '1612324737875'
  alias: Set Location
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 05:30:00
  condition: []
  action:
  - service: script.toggle
    data: {}
    entity_id: script.set_location
  mode: single
- id: '1612324864484'
  alias: Day Counter
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: counter.increment
    data: {}
    entity_id: counter.road
  - service: counter.increment
    data: {}
    entity_id: counter.filter_hose
  - service: counter.increment
    data: {}
    entity_id: counter.house_filter
  - service: counter.increment
    data: {}
    entity_id: counter.black_tank_days
  mode: single
- id: '1612544414943'
  alias: Set Location Travel Mode
  description: This sets the location based on my phone activity and SSID
  trigger:
  - platform: state
    entity_id: device_tracker.life360_taylor_snow
    from: Driving
    to: '*'
  condition:
  - condition: state
    entity_id: sensor.taylors_iphone_ssid
    state: MenTay Escape
    attribute: friendly_name
  action:
  - service: script.set_location
    data: {}
  mode: parallel
  max: 10
- id: '1612576142631'
  alias: Auto Away
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '1'
  condition:
  - condition: state
    entity_id: person.mendy_snow
    state: Away
  - condition: state
    entity_id: person.taylor_snow
    state: Away
  action:
  - service: input_select.select_option
    data:
      option: Away
    entity_id: input_select.mode
  mode: parallel
  max: 5
- id: '1612576304570'
  alias: Home Taylor
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '1'
  condition:
  - condition: state
    entity_id: person.taylor_snow
    state: Home
  action:
  - service: input_select.select_option
    data:
      option: Home
    entity_id: input_select.mode
  mode: single
- id: '1612576398649'
  alias: Home Mendy
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '1'
  condition:
  - condition: state
    entity_id: person.mendy_snow
    state: Home
  action:
  - service: input_select.select_option
    data:
      option: Home
    entity_id: input_select.mode
  mode: single
- id: '1613098718367'
  alias: Watts Remaining Announcement
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.watts_remaining
    below: '1000'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: ' Just a heads up, there is currently only {{ states("sensor.watts_remaining")
        }} watts remaining, out of 3600'
      data:
        type: tts
      target:
      - media_player.everywhere
  mode: single
- id: '1613098856169'
  alias: Battery Full
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.voltage
    above: '14'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: ' The battery appears to be charged'
      data:
        type: tts
      target:
      - media_player.everywhere
  mode: single
- id: '1613099803542'
  alias: Motion Detected Tongue
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.000_cell_motion_detection
    to: 'On'
    from: '*'
  condition: []
  action:
  - service: notify.mobile_app_taylors_iphone
    data:
      message: Motion Detected at the front of the RV
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.tongue
  mode: single
